var annotated_dup =
[
    [ "Attribute", "class_attribute.html", "class_attribute" ],
    [ "AttributeRenderer", "class_attribute_renderer.html", "class_attribute_renderer" ],
    [ "AttributeType", "class_attribute_type.html", "class_attribute_type" ],
    [ "AutoSaveManager", "class_auto_save_manager.html", "class_auto_save_manager" ],
    [ "BasicElement", "class_basic_element.html", "class_basic_element" ],
    [ "BezierControlPoint", "class_bezier_control_point.html", "class_bezier_control_point" ],
    [ "ConnectionGraphicsItem", "class_connection_graphics_item.html", "class_connection_graphics_item" ],
    [ "ConnectionLine", "class_connection_line.html", "class_connection_line" ],
    [ "ConnectionPoint", "class_connection_point.html", "class_connection_point" ],
    [ "DiagramFileManager", "class_diagram_file_manager.html", "class_diagram_file_manager" ],
    [ "DiagramScene", "class_diagram_scene.html", "class_diagram_scene" ],
    [ "DiagramSerializer", "class_diagram_serializer.html", "class_diagram_serializer" ],
    [ "DiagramView", "class_diagram_view.html", "class_diagram_view" ],
    [ "DraggableButton", "class_draggable_button.html", "class_draggable_button" ],
    [ "ElementFactory", "class_element_factory.html", null ],
    [ "ElementGraphicsItem", "class_element_graphics_item.html", "class_element_graphics_item" ],
    [ "ElementRendererFactory", "class_element_renderer_factory.html", null ],
    [ "Entity", "class_entity.html", "class_entity" ],
    [ "EntityRenderer", "class_entity_renderer.html", "class_entity_renderer" ],
    [ "IElementObserver", "class_i_element_observer.html", "class_i_element_observer" ],
    [ "IElementRenderer", "class_i_element_renderer.html", "class_i_element_renderer" ],
    [ "MainWindow", "class_main_window.html", "class_main_window" ],
    [ "PropertiesPanel", "class_properties_panel.html", "class_properties_panel" ],
    [ "PropertyCommand", "class_property_command.html", null ],
    [ "QuickAccessToolbar", "class_quick_access_toolbar.html", "class_quick_access_toolbar" ],
    [ "Relationship", "class_relationship.html", "class_relationship" ],
    [ "RelationshipConnectionLine", "class_relationship_connection_line.html", "class_relationship_connection_line" ],
    [ "RelationshipConnectionLineGraphicsItem", "class_relationship_connection_line_graphics_item.html", "class_relationship_connection_line_graphics_item" ],
    [ "RelationshipEnd", "class_relationship_end.html", "class_relationship_end" ],
    [ "RelationshipRenderer", "class_relationship_renderer.html", "class_relationship_renderer" ]
];