name: Windows Build

on:
  workflow_call:
    inputs:
      package_zip:
        description: "Create a ZIP package for release"
        required: false
        type: boolean
        default: false
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install Qt
      uses: jurplel/install-qt-action@v4
      with:
        version: '6.9.3'
        host: windows
        target: desktop
        arch: win64_msvc2022_64

    - name: Configure CMake
      run: cmake -B build -S . -DCMAKE_BUILD_TYPE=Release

    - name: Build
      run: cmake --build build --config Release

    - name: Deploy Qt dependencies
      run: |
        mkdir package
        copy build\Release\DERDesigner.exe package\
        windeployqt --release package\DERDesigner.exe

    - name: Zip package
      if: ${{ inputs.package_zip }}
      run: Compress-Archive -Path package\* -DestinationPath DERDesigner-windows.zip

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: DERDesigner-windows
        path: ${{ inputs.package_zip && 'DERDesigner-windows.zip' || 'package\\' }}