name: Test Qt Install

on:
  workflow_dispatch:

jobs:
  test-windows:
    runs-on: windows-latest

    steps:
      - name: Install aqt
        shell: pwsh
        run: pip install aqtinstall

      - name: List available Qt versions
        shell: pwsh
        run: python -m aqt list-qt windows desktop