name: Test Qt Install

on:
  push:
    branches: ["test-qt-install"]
  workflow_dispatch:

jobs:
  test-windows:
    runs-on: windows-latest

    steps:
      - name: Install aqt
        shell: pwsh
        run: pip install aqtinstall

      - name: List available architectures for 6.7.2
        shell: pwsh
        run: python -m aqt list-qt windows desktop --arch 6.7.2
